# Use this docker-compose file for dev environment
version: '3'
services:
  web:
    build: .
    image: contribution-tracker
    ports:
      - "3000:3000"
    dns: "8.8.8.8"
    volumes:
      - ".:/app"
    env_file: .env
    command: bash -c "rake db:create && rake db:migrate && rails s"
