version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    expose:
      - "3000"
    dns: "8.8.8.8"
    volumes:
      - ".:/app"
    env_file: .env
    depends_on:
      - redis
    external_links:
      - postgres:db
    command: bash -c "bundle exec rake assets:precompile && bundle exec rake db:create && bundle exec wheneverize . && bundle exec rake db:migrate && bundle exec rails s"
    networks:
      - production
    restart: always

  redis:
    image: redis:4.0-alpine
    external_links:
      - postgres:db
    networks:
      - production
    ports:
      - '6379:6379'

  sidekiq:
    build: .
    command: bash -c "sidekiq -C condig/sidekiq.yml.erb"
    depends_on:
      - redis
    external_links:
      - postgres:db
    volumes:
      - '.:/app'
    networks:
      - production
    env_file:
      - '.env'








networks:
  production:
    external: true
# Refer to: https://viky.co.in/2017/12/18/link-external-containers-using-docker-compose/
# Useful commands:
# docker network create production
# docker network connect production postgres
