# Use this docker-compose file for dev environment
version: '2'
services:
  web:
    build: .
    image: contribution-tracker
    ports:
      - "3000:3000"
    dns: "8.8.8.8"
    volumes:
      - ".:/app"
    links:
      - db
    env_file: .env
    command: bash -c "bundle exec rake db:create && rake db:migrate && rails s"
    
  db:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=thanks123"
